In [1]:
import pandas as pd
pd.options.display.max_rows = 100

In [2]:
df = pd.read_csv('saved_csv/compare_test_df.csv', index_col=0)
df

     Actual  Predicted  Probabilities
0         0          1       0.997201
1         1          1       0.998617
2         1          1       0.974159
3         0          0       0.000048
4         0          0       0.000573
..      ...        ...            ...
619       1          1       0.994787
620       1          1       0.998777
621       1          1       0.998168
622       1          1       0.999907
623       1          1       0.889917

[624 rows x 3 columns]

In [3]:
df.loc[df['Predicted'] != df['Actual'], "Right?"] = "wrong"
df.loc[df['Predicted'] == df['Actual'], "Right?"] = "correct"

In [4]:
df.head()

   Actual  Predicted  Probabilities   Right?
0       0          1       0.997201    wrong
1       1          1       0.998617  correct
2       1          1       0.974159  correct
3       0          0       0.000048  correct
4       0          0       0.000573  correct

In [5]:
df['Right?'].value_counts()

correct    558
wrong       66
Name: Right?, dtype: int64

In [6]:
df_wrong = df.loc[df['Right?'] == "wrong"]
df_wrong

     Actual  Predicted  Probabilities Right?
0         0          1       0.997201  wrong
31        0          1       0.755906  wrong
32        1          0       0.122652  wrong
34        0          1       0.991962  wrong
35        0          1       0.833358  wrong
37        1          0       0.005426  wrong
57        0          1       0.927552  wrong
63        0          1       0.971036  wrong
80        0          1       0.684913  wrong
84        0          1       0.681035  wrong
93        0          1       0.925963  wrong
102       0          1       0.553343  wrong
106       0          1       0.774768  wrong
124       0          1       0.982253  wrong
133       0          1       0.563543  wrong
141       1          0       0.082885  wrong
155       1          0       0.430811  wrong
160       0          1       0.509906  wrong
169       0          1       0.641854  wrong
173       0          1       0.998607  wrong
188       0          1       0.836240  wrong
191       0          1       0.648238  wrong
199       0          1       0.930479  wrong
203       0          1       0.999271  wrong
215       0          1       0.997953  wrong
227       0          1       0.994390  wrong
238       0          1       0.656419  wrong
243       0          1       0.758217  wrong
246       0          1       0.841444  wrong
285       0          1       0.990881  wrong
294       0          1       0.666019  wrong
298       0          1       0.998551  wrong
299       0          1       0.898835  wrong
302       0          1       0.913816  wrong
315       0          1       0.539513  wrong
316       0          1       0.990168  wrong
322       0          1       0.857398  wrong
326       0          1       0.999067  wrong
357       0          1       0.748268  wrong
360       1          0       0.431009  wrong
368       1          0       0.435626  wrong
378       1          0       0.055688  wrong
382       0          1       0.851083  wrong
385       0          1       0.876397  wrong
390       0          1       0.873337  wrong
396       1          0       0.084768  wrong
400       1          0       0.001192  wrong
411       0          1       0.788834  wrong
414       0          1       0.696569  wrong
458       0          1       0.898310  wrong
476       1          0       0.305076  wrong
494       0          1       0.930255  wrong
518       1          0       0.049908  wrong
522       1          0       0.117866  wrong
526       0          1       0.955105  wrong
531       0          1       0.996863  wrong
535       0          1       0.969230  wrong
537       0          1       0.995223  wrong
539       0          1       0.750558  wrong
554       0          1       0.988048  wrong
570       0          1       0.996665  wrong
580       0          1       0.999237  wrong
584       1          0       0.381659  wrong
589       0          1       0.997926  wrong
593       1          0       0.210624  wrong
609       0          1       0.980494  wrong

In [15]:
df_right = df.loc[df['Right?'] == "correct"]
df_right.head(20)

    Actual  Predicted  Probabilities   Right?
1        1          1       0.998617  correct
2        1          1       0.974159  correct
3        0          0       0.000048  correct
4        0          0       0.000573  correct
5        1          1       0.721699  correct
6        0          0       0.025416  correct
7        0          0       0.019322  correct
8        0          0       0.000882  correct
9        1          1       0.981092  correct
10       1          1       0.999898  correct
11       0          0       0.247327  correct
12       0          0       0.000013  correct
13       1          1       0.997572  correct
14       1          1       0.987785  correct
15       0          0       0.002130  correct
16       0          0       0.000274  correct
17       0          0       0.000669  correct
18       1          1       0.998540  correct
19       1          1       0.999976  correct
20       1          1       0.999904  correct

In [17]:
df_right.sort_values(by='Probabilities')

     Actual  Predicted  Probabilities   Right?
608       0          0   1.618850e-07  correct
216       0          0   2.030896e-07  correct
457       0          0   1.863194e-06  correct
555       0          0   3.815203e-06  correct
214       0          0   1.001604e-05  correct
..      ...        ...            ...      ...
453       1          1   9.999950e-01  correct
353       1          1   9.999953e-01  correct
557       1          1   9.999973e-01  correct
211       1          1   9.999973e-01  correct
92        1          1   9.999976e-01  correct

[558 rows x 4 columns]

In [18]:
df_right_1 = df_right.loc[df_right['Actual'] == 1]
df_right_1.head(10)

    Actual  Predicted  Probabilities   Right?
1        1          1       0.998617  correct
2        1          1       0.974159  correct
5        1          1       0.721699  correct
9        1          1       0.981092  correct
10       1          1       0.999898  correct
13       1          1       0.997572  correct
14       1          1       0.987785  correct
18       1          1       0.998540  correct
19       1          1       0.999976  correct
20       1          1       0.999904  correct

In [19]:
df_right_1.sort_values(by='Probabilities')

     Actual  Predicted  Probabilities   Right?
616       1          1       0.507310  correct
45        1          1       0.523363  correct
568       1          1       0.599135  correct
138       1          1       0.620336  correct
196       1          1       0.648019  correct
..      ...        ...            ...      ...
453       1          1       0.999995  correct
353       1          1       0.999995  correct
211       1          1       0.999997  correct
557       1          1       0.999997  correct
92        1          1       0.999998  correct

[376 rows x 4 columns]

In [20]:
df_right_1.describe()

       Actual  Predicted  Probabilities
count   376.0      376.0     376.000000
mean      1.0        1.0       0.969766
std       0.0        0.0       0.075669
min       1.0        1.0       0.507310
25%       1.0        1.0       0.984242
50%       1.0        1.0       0.998285
75%       1.0        1.0       0.999779
max       1.0        1.0       0.999998

In [25]:
df_right_1.loc[df_right_1['Probabilities']<=0.6]

     Actual  Predicted  Probabilities   Right?
45        1          1       0.523363  correct
568       1          1       0.599135  correct
616       1          1       0.507310  correct

In [7]:
df_wrong_1 = df_wrong.loc[df_wrong['Actual'] == 1]
df_wrong_1

     Actual  Predicted  Probabilities Right?
32        1          0       0.122652  wrong
37        1          0       0.005426  wrong
141       1          0       0.082885  wrong
155       1          0       0.430811  wrong
360       1          0       0.431009  wrong
368       1          0       0.435626  wrong
378       1          0       0.055688  wrong
396       1          0       0.084768  wrong
400       1          0       0.001192  wrong
476       1          0       0.305076  wrong
518       1          0       0.049908  wrong
522       1          0       0.117866  wrong
584       1          0       0.381659  wrong
593       1          0       0.210624  wrong

In [14]:
df_wrong_1.sort_values(by='Probabilities')

     Actual  Predicted  Probabilities Right?
400       1          0       0.001192  wrong
37        1          0       0.005426  wrong
518       1          0       0.049908  wrong
378       1          0       0.055688  wrong
141       1          0       0.082885  wrong
396       1          0       0.084768  wrong
522       1          0       0.117866  wrong
32        1          0       0.122652  wrong
593       1          0       0.210624  wrong
476       1          0       0.305076  wrong
584       1          0       0.381659  wrong
155       1          0       0.430811  wrong
360       1          0       0.431009  wrong
368       1          0       0.435626  wrong

In [9]:
df_wrong_1.describe()

       Actual  Predicted  Probabilities
count    14.0       14.0      14.000000
mean      1.0        0.0       0.193942
std       0.0        0.0       0.167850
min       1.0        0.0       0.001192
25%       1.0        0.0       0.062487
50%       1.0        0.0       0.120259
75%       1.0        0.0       0.362513
max       1.0        0.0       0.435626

In [10]:
df_wrong_0 = df_wrong.loc[df_wrong['Actual'] == 0]
df_wrong_0

     Actual  Predicted  Probabilities Right?
0         0          1       0.997201  wrong
31        0          1       0.755906  wrong
34        0          1       0.991962  wrong
35        0          1       0.833358  wrong
57        0          1       0.927552  wrong
63        0          1       0.971036  wrong
80        0          1       0.684913  wrong
84        0          1       0.681035  wrong
93        0          1       0.925963  wrong
102       0          1       0.553343  wrong
106       0          1       0.774768  wrong
124       0          1       0.982253  wrong
133       0          1       0.563543  wrong
160       0          1       0.509906  wrong
169       0          1       0.641854  wrong
173       0          1       0.998607  wrong
188       0          1       0.836240  wrong
191       0          1       0.648238  wrong
199       0          1       0.930479  wrong
203       0          1       0.999271  wrong
215       0          1       0.997953  wrong
227       0          1       0.994390  wrong
238       0          1       0.656419  wrong
243       0          1       0.758217  wrong
246       0          1       0.841444  wrong
285       0          1       0.990881  wrong
294       0          1       0.666019  wrong
298       0          1       0.998551  wrong
299       0          1       0.898835  wrong
302       0          1       0.913816  wrong
315       0          1       0.539513  wrong
316       0          1       0.990168  wrong
322       0          1       0.857398  wrong
326       0          1       0.999067  wrong
357       0          1       0.748268  wrong
382       0          1       0.851083  wrong
385       0          1       0.876397  wrong
390       0          1       0.873337  wrong
411       0          1       0.788834  wrong
414       0          1       0.696569  wrong
458       0          1       0.898310  wrong
494       0          1       0.930255  wrong
526       0          1       0.955105  wrong
531       0          1       0.996863  wrong
535       0          1       0.969230  wrong
537       0          1       0.995223  wrong
539       0          1       0.750558  wrong
554       0          1       0.988048  wrong
570       0          1       0.996665  wrong
580       0          1       0.999237  wrong
589       0          1       0.997926  wrong
609       0          1       0.980494  wrong

In [11]:
df_wrong_0.describe()

       Actual  Predicted  Probabilities
count    52.0       52.0      52.000000
mean      0.0        1.0       0.857740
std       0.0        0.0       0.147561
min       0.0        1.0       0.509906
25%       0.0        1.0       0.754569
50%       0.0        1.0       0.906326
75%       0.0        1.0       0.991151
max       0.0        1.0       0.999271