In [33]:
import pandas as pd
pd.options.display.max_rows = 100
pd.set_option("precision", 6)
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('saved_csv/compare_test_df.csv', index_col=0)
df

     Actual  Predicted  Probabilities
0         0          1       0.997201
1         1          1       0.998617
2         1          1       0.974159
3         0          0       0.000048
4         0          0       0.000573
..      ...        ...            ...
619       1          1       0.994787
620       1          1       0.998777
621       1          1       0.998168
622       1          1       0.999907
623       1          1       0.889917

[624 rows x 3 columns]

In [3]:
# Add a column to indicate whether the model predict correctly or not
df.loc[df['Predicted'] != df['Actual'], "Right?"] = "wrong"
df.loc[df['Predicted'] == df['Actual'], "Right?"] = "correct"

In [29]:
df.head()

   Actual  Predicted  Probabilities   Right?
0       0          1       0.997201    wrong
1       1          1       0.998617  correct
2       1          1       0.974159  correct
3       0          0       0.000048  correct
4       0          0       0.000573  correct

In [5]:
df['Right?'].value_counts()

correct    558
wrong       66
Name: Right?, dtype: int64

In [54]:
# Sub-df for predict wrong
df_wrong = df.loc[df['Right?'] == "wrong"]
df_wrong.head()

    Actual  Predicted  Probabilities Right?
0        0          1       0.997201  wrong
31       0          1       0.755906  wrong
32       1          0       0.122652  wrong
34       0          1       0.991962  wrong
35       0          1       0.833358  wrong

In [56]:
# Sub-df for predict correctly
df_right = df.loc[df['Right?'] == "correct"]
df_right.head()

   Actual  Predicted  Probabilities   Right?
1       1          1       0.998617  correct
2       1          1       0.974159  correct
3       0          0       0.000048  correct
4       0          0       0.000573  correct
5       1          1       0.721699  correct

In [58]:
# sub-df: predict(1)  and correctly
df_right_1 = df_right.loc[df_right['Actual'] == 1]
df_right_1.head()

    Actual  Predicted  Probabilities   Right?
1        1          1       0.998617  correct
2        1          1       0.974159  correct
5        1          1       0.721699  correct
9        1          1       0.981092  correct
10       1          1       0.999898  correct

In [20]:
df_right_1.describe()

       Actual  Predicted  Probabilities
count   376.0      376.0     376.000000
mean      1.0        1.0       0.969766
std       0.0        0.0       0.075669
min       1.0        1.0       0.507310
25%       1.0        1.0       0.984242
50%       1.0        1.0       0.998285
75%       1.0        1.0       0.999779
max       1.0        1.0       0.999998

- min is 50.73%

In [52]:
df_right_1.loc[df_right_1['Probabilities']<=0.6].sort_values(by='Probabilities')

     Actual  Predicted  Probabilities   Right?
616       1          1       0.507310  correct
45        1          1       0.523363  correct
568       1          1       0.599135  correct

In [7]:
# sub-df: false negative
df_wrong_1 = df_wrong.loc[df_wrong['Actual'] == 1]
df_wrong_1

     Actual  Predicted  Probabilities Right?
32        1          0       0.122652  wrong
37        1          0       0.005426  wrong
141       1          0       0.082885  wrong
155       1          0       0.430811  wrong
360       1          0       0.431009  wrong
368       1          0       0.435626  wrong
378       1          0       0.055688  wrong
396       1          0       0.084768  wrong
400       1          0       0.001192  wrong
476       1          0       0.305076  wrong
518       1          0       0.049908  wrong
522       1          0       0.117866  wrong
584       1          0       0.381659  wrong
593       1          0       0.210624  wrong

In [14]:
df_wrong_1.sort_values(by='Probabilities')

     Actual  Predicted  Probabilities Right?
400       1          0       0.001192  wrong
37        1          0       0.005426  wrong
518       1          0       0.049908  wrong
378       1          0       0.055688  wrong
141       1          0       0.082885  wrong
396       1          0       0.084768  wrong
522       1          0       0.117866  wrong
32        1          0       0.122652  wrong
593       1          0       0.210624  wrong
476       1          0       0.305076  wrong
584       1          0       0.381659  wrong
155       1          0       0.430811  wrong
360       1          0       0.431009  wrong
368       1          0       0.435626  wrong

In [9]:
df_wrong_1.describe()

       Actual  Predicted  Probabilities
count    14.0       14.0      14.000000
mean      1.0        0.0       0.193942
std       0.0        0.0       0.167850
min       1.0        0.0       0.001192
25%       1.0        0.0       0.062487
50%       1.0        0.0       0.120259
75%       1.0        0.0       0.362513
max       1.0        0.0       0.435626

- false negative in the range of 1.192% to 43.45%

In [60]:
df2 = pd.read_csv('saved_csv/compare_val_df.csv', index_col=0)
df2

    Actual  Predicted  Probabilities
0        1          1       0.999788
1        0          0       0.011108
2        1          1       0.836921
3        0          0       0.008234
4        1          1       0.963182
5        0          0       0.002260
6        0          0       0.000042
7        1          1       0.981357
8        0          1       0.568237
9        0          0       0.000317
10       1          1       0.998771
11       1          1       0.999180
12       0          0       0.000156
13       1          1       0.862494
14       0          0       0.000049
15       1          1       0.991182

In [61]:
df2.loc[df2['Actual'] != df2['Predicted']]

   Actual  Predicted  Probabilities
8       0          1       0.568237

- based on the test and val result: threshold can be set between P<60% (for the probaility of predicting if patients have pneumonia)

In [42]:
df_right_0 = df_right.loc[df_right['Actual'] == 0]
df_right_0.head(10)

    Actual  Predicted  Probabilities   Right?
3        0          0       0.000048  correct
4        0          0       0.000573  correct
6        0          0       0.025416  correct
7        0          0       0.019322  correct
8        0          0       0.000882  correct
11       0          0       0.247327  correct
12       0          0       0.000013  correct
15       0          0       0.002130  correct
16       0          0       0.000274  correct
17       0          0       0.000669  correct

In [43]:
df_right_0.describe()

       Actual  Predicted  Probabilities
count   182.0      182.0   1.820000e+02
mean      0.0        0.0   6.402357e-02
std       0.0        0.0   1.167572e-01
min       0.0        0.0   1.618850e-07
25%       0.0        0.0   8.443139e-04
50%       0.0        0.0   6.682145e-03
75%       0.0        0.0   4.747808e-02
max       0.0        0.0   4.935580e-01

In [62]:
# fig = plt.figure()
# ax = fig.add_subplot(111)
# ax.boxplot(df_wrong_1['Probabilities'], vert=False);

In [63]:
df_wrong_0 = df_wrong.loc[df_wrong['Actual'] == 0]
df_wrong_0.head()

    Actual  Predicted  Probabilities Right?
0        0          1       0.997201  wrong
31       0          1       0.755906  wrong
34       0          1       0.991962  wrong
35       0          1       0.833358  wrong
57       0          1       0.927552  wrong

In [64]:
df_wrong_0.describe()

       Actual  Predicted  Probabilities
count    52.0       52.0      52.000000
mean      0.0        1.0       0.857740
std       0.0        0.0       0.147561
min       0.0        1.0       0.509906
25%       0.0        1.0       0.754569
50%       0.0        1.0       0.906326
75%       0.0        1.0       0.991151
max       0.0        1.0       0.999271